# Generated by Django 4.2.11 on 2024-03-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Adı')),
                ('max_flight_time', models.FloatField(verbose_name='Maksimum Uçuş Süresi (saat)')),
                ('weight', models.FloatField(verbose_name='Ağırlık (kg)')),
                ('communication_tech', models.CharField(choices=[('wifi', 'Wi-Fi'), ('radio', 'Radio'), ('satellite', 'Satellite'), ('cellular', 'Cellular')], max_length=100, verbose_name='İletişim Teknolojileri')),
                ('operational_altitude', models.IntegerField(verbose_name='Operasyonel İrtifa (feet)')),
                ('max_speed', models.IntegerField(verbose_name='Maksimum Hız (km/saat)')),
                ('payload_capacity', models.FloatField(verbose_name='Yük Kapasitesi (kg)')),
                ('endurance', models.FloatField(verbose_name='Dayanıklılık (saat)')),
                ('control_system', models.CharField(choices=[('manual', 'Manuel'), ('autonomous', 'Otonom'), ('remote_control', 'Uzaktan Kontrol')], max_length=100, verbose_name='Kontrol Sistemi')),
                ('applications', models.TextField(verbose_name='Uygulama Alanları')),
                ('onboard_computers', models.IntegerField(blank=True, null=True, verbose_name='Yüklü Bilgisayar Sayısı')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uavs', to='payment.payment', verbose_name='Ödeme')),
            ],
        ),
    ]
