# Generated by Django 4.2.11 on 2024-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Adı')),
                ('max_flight_time', models.FloatField(verbose_name='Maksimum Uçuş Süresi (saat)')),
                ('weight', models.FloatField(verbose_name='Ağırlık (kg)')),
                ('communication_tech', models.CharField(max_length=100, verbose_name='İletişim Teknolojileri')),
                ('operational_altitude', models.IntegerField(verbose_name='Operasyonel İrtifa (feet)')),
                ('max_speed', models.IntegerField(verbose_name='Maksimum Hız (km/saat)')),
                ('payload_capacity', models.FloatField(verbose_name='Yük Kapasitesi (kg)')),
                ('endurance', models.FloatField(verbose_name='Dayanıklılık (saat)')),
                ('control_system', models.CharField(max_length=100, verbose_name='Kontrol Sistemi')),
                ('applications', models.TextField(verbose_name='Uygulama Alanları')),
                ('onboard_computers', models.IntegerField(blank=True, null=True, verbose_name='Yüklü Bilgisayar Sayısı')),
            ],
        ),
    ]
