# Generated by Django 4.2.11 on 2024-03-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Uav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uav',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Mevcut'),
        ),
    ]
