# Generated by Django 4.2.11 on 2024-03-20 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Uav', '0002_uav_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uav',
            name='is_available',
        ),
    ]
