# Generated by Django 4.2.11 on 2024-03-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('currency', models.CharField(choices=[('TRY', 'TL'), ('USD', 'Dolar'), ('EUR', 'Euro')], max_length=3, verbose_name='Para Birimi')),
                ('date', models.DateField(verbose_name='SonGeçerlilik Tarihi')),
            ],
        ),
    ]
