# Generated by Django 4.2.11 on 2024-03-19 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Uav', '0002_uav_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(verbose_name='Bitiş Tarihi')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='Uav.uav', verbose_name='UAV')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
