# Generated by Django 4.2.11 on 2024-03-19 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
